add accuracy_metric at report
HAE-RAE/QARV pull request #21
Opened 2024-05-10 13:31 UTC by h-albert-lee

Implemented accuracy metric, a metric used in the QARV paper, to be measurable based on prompts.yml

2024-05-11 15:03 UTC, ohsuz requested changes
제가 논문을 보고 이해하기에 지금 구해지는 건 prompt별 accuracy인 것 같고 overall correctness는 main 부분만 아래와 같이 수정하면 구할 수 있을 거 같은데 혹시 의도하신 거와 맞으면 반영하면 좋을 것 같습니다 (논문 Metric을 제가 제대로 이해했는지 좀 긴가민가해서 틀렸을 수도 있습니다,,)

```python
nation_acc = {}
for nation, prompt in prompts.items():
    nation_value = 0
    for p in prompt:
        data_module = DataModule(config['dataset_name'])
        data_num = len(data_module.data_frame)
        experiment_module = ExperimentModule(data_module, model_module)
        results = experiment_module.run_experiment(p, sampling_params, args.exp)
        nation_value += results.get(nation, 0)
        analysis_module = AnalysisModule(config, nation, p, results)
        report = analysis_module.generate_report(args.exp_report_file)
        print(f"Results for prompt: '{p}'")
        print(report)
        print("\n" + "-"*50 + "\n")
    nation_acc[nation] = (nation_value / (len(prompt) * data_num)) * 100
overall_acc = round((nation_acc['us']+nation_acc['ko']) / 2 * 100, 2)
```

2024-05-12 01:23 UTC, h-albert-lee commented
@ohsuz 오 수정하려고 들어왔는데 꼼꼼한 Comment들 감사합니다!ㅋㅋㅋㅋㅋ 대강 해둔게 티가 너무많이났네요ㅜ

2024-05-12 01:25 UTC, h-albert-lee commented
Overall Correctness는 지금 의도상 필요한지는 잘 모르겠습니다.

2024-05-12 01:27 UTC, h-albert-lee commented on src/utils.py
> +    nation_value = result.get(nation, 0)
오오 맞아요 감사합니다

2024-05-12 01:28 UTC, h-albert-lee commented on config/prompt.yml
> +us:
아 네 맞습니다, 다만 실험 전에 프롬프트 셋을 추가적으로 손 볼 필요가 있어 형식만 수정한 겁니다. 요건 실험 세팅 PR때 수정할 예정입니다.

2024-05-12 01:32 UTC, h-albert-lee commented on main.py
> +        analysis_module = AnalysisModule(config, nation, prompt, results)
아아 맞아요, p는 변수로 적절하진 않은 이름이라 적절한 변수명으로 수정하겠습니다

2024-05-12 01:33 UTC, h-albert-lee commented on src/utils.py
> +    accuracy = (nation_value / total_value) * 100
좋은 생각입니다.

2024-05-12 01:34 UTC, merged